### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by pkoelemij**
Fixed `public async Task<bool> DownloadSDE()` by adding using statements because the objects kept a lock on the local files. Fixed `public async Task<bool> Import()` possible leak by adding a using statement. The rest is prettifying up to normal standards.

### CODE REVIEW

**Comment by pkoelemij** [comment]
@pfh59 How do I sign the cla?

**Comment by pfh59** [comment]
recheck

**Comment by pfh59** [comment]
wait I check security rules

**Comment by pfh59** [comment]
recheck

**Review by pfh59 — APPROVED** [review]

**Comment by pfh59** [comment]
@pkoelemij PR is approved, I had your name to the CLA list. I don't why it's not working and I don't have time to search now.
Thank for your contribution

**Pull request merged**
